// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ModifiedData2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifiedData2));
        
        string IMigrationMetadata.Id
        {
            get { return "202502070515588_Modified-Data2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
